apiVersion: v1
kind: ConfigMap
metadata:
  name: go-service-config
  namespace: urlshortener
data:
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  PYTHON_SERVICE_URL: "http://python-service:5000"
  PORT: "8000"
