apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: urlshortener-ingress
  namespace: {{ .Values.global.namespace }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /()(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ .Values.pythonService.name }}
                port:
                  number: {{ .Values.pythonService.port }}
          - path: /go(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ .Values.goService.name }}
                port:
                  number: {{ .Values.goService.port }}
          - path: /node(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ .Values.nodeService.name }}
                port:
                  number: {{ .Values.nodeService.port }}
