global:
  namespace: urlshortener
  imageRegistry: ""   # DockerHub username — set via --set global.imageRegistry=yourusername
  imageTag: latest

ingress:
  host: urlshortener.local
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "60"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "60"

redis:
  image: redis:7-alpine
  port: 6379
  storage: 1Gi
  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "300m"
      memory: "256Mi"

pythonService:
  name: python-service
  image: python-service
  pullPolicy: IfNotPresent
  replicas: 1
  port: 5000
  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"
  hpa:
    minReplicas: 1
    maxReplicas: 5
    targetCPU: 70
    targetMemory: 80
  env:
    FLASK_ENV: "production"
  secrets:
    SECRET_KEY: "change-me-in-production"

goService:
  name: go-service
  image: go-service
  pullPolicy: IfNotPresent
  replicas: 1
  port: 8000
  resources:
    requests:
      cpu: "100m"
      memory: "64Mi"
    limits:
      cpu: "500m"
      memory: "256Mi"
  hpa:
    minReplicas: 1
    maxReplicas: 5
    targetCPU: 70
    targetMemory: 80

nodeService:
  name: node-service
  image: node-service
  pullPolicy: IfNotPresent
  replicas: 1
  port: 3000
  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"
  hpa:
    minReplicas: 1
    maxReplicas: 5
    targetCPU: 70
    targetMemory: 80
  env:
    NODE_ENV: "production"
